export enum TLCursor {
  Default = 'default',
  Pointer = 'pointer',
  Cross = 'crosshair',
  Grab = 'grab',
  Grabbing = 'grabbing',
  ResizeEdge = 'resize-edge',
  ResizeCorner = 'resize-corner',
  Text = 'text',
  Move = 'move',
  EwResize = 'ew-resize',
  NsResize = 'ns-resize',
  NeswResize = 'nesw-resize',
  NwseResize = 'nwse-resize',
}
