export type TLCursor =
  | 'default'
  | 'pointer'
  | 'cross'
  | 'grab'
  | 'grabbing'
  | 'resize-edge'
  | 'resize-corner'
  | 'text'
  | 'move'
  | 'ew-resize'
  | 'ns-resize'
  | 'nesw-resize'
  | 'nwse-resize'
